name: Build and publish container images

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-base-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          file: toolbox/fedora-base/Containerfile
          context: toolbox/fedora-base/
          push: true
          tags: ghcr.io/scudelletti/fedora-base-toolbox:latest
  build-and-push-toolbox:
    needs:
      - build-and-push-base-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        name:
          - devtools
          - editors
          - pdf-tools
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          file: toolbox/${{ matrix.name }}/Containerfile
          context: toolbox/${{ matrix.name }}/
          push: true
          tags: ghcr.io/scudelletti/${{ matrix.name }}-toolbox:latest
